baseURL: "https://cosimameyer.com/"
languageCode: en-us
pagerSize: 6
theme: 
  - "portio-hugo"
title: "Cosima Meyer – Data Scientist, Speaker & Community Builder"
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
menu:
  main:
    - name: About
      url: '#about'
      weight: 1
    - name: Speaking
      url: '#testimonial'
      weight: 2
    - name: Media
      url: '#media'
      weight: 3
    - name: Open Source
      url: '#portfolio'
      weight: 4
    - name: Writing
      url: '#post'
      weight: 5
  sitemap:
    # - name: About me
    #   url: about
    #   weight: 1
    # - name: Frequently Ask Question
    #   url: '#'
    #   weight: 2
    - name: Privacy & Policy
      url: '/privacy/privacy'
      weight: 1
    - name: Terms
      url: '/privacy/terms'
      weight: 2
params:
  description: "Senior Data Scientist at SAP, conference speaker, and community builder in the R and Python ecosystem. I speak on explainable ML, NLP, open-source development, and inclusion in tech."
  blogPageURL: post
  contactLink: contact
  copyright: All rights reserved © Cosima Meyer 2026
  footerLogo: images/contact/widget-logo.png
  logo: images/site-navigation/logo.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/cosimameyer/
      weight: 1
    - icon: fa-github
      url: https://github.com/cosimameyer
      weight: 3
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: monokailight
    tabWidth: 4
taxonomies:
  category: category
  tag: tags
outputs:
  home: ["HTML", "RSS", "JSON", "WebAppManifest"]
  section: [ "HTML", "RSS" ]
  taxonomy: [ "HTML", "RSS" ]
  taxonomyTerm: [ "HTML", "RSS" ]
ignoreErrors: ["error-remote-getjson"]