baseURL: "https://cosimameyer.com/"
languageCode: en-us
pagerSize: 6
theme: 
  - "portio-hugo"
title: Cosima Meyer
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: Portfolio
      url: '#portfolio'
      weight: 4
    - name: Resume
      url: '#resume'
      weight: 5
    # - name: Skills
    #   url: '#skills' 
    #   weight: 6
    - name: Talks
      url: '#testimonial'
      weight: 6
    - name: Blog
      url: '#post'
      weight: 7
    - name: Media
      url: '#service'
      weight: 8
    - name: Gallery
      url: 'https://gallery.cosimameyer.com'
      weight: 9
    - name: overviewR
      url: 'https://cosimameyer.github.io/overviewR/'
      weight: 10
    - name: overviewpy
      url: 'https://cosimameyer.github.io/overviewpy/'
      weight: 11
    # - name: Contact
    #   url: '#contact'
    #   weight: 8
  sitemap:
    # - name: About me
    #   url: about
    #   weight: 1
    # - name: Frequently Ask Question
    #   url: '#'
    #   weight: 2
    - name: Privacy & Policy
      url: '/privacy/privacy'
      weight: 1
    - name: Terms
      url: '/privacy/terms'
      weight: 2
params:
  blogPageURL: post
  contactLink: contact
  copyright: All right reserved copyright © Cosima Meyer 2024
  footerLogo: images/contact/widget-logo.png
  logo: images/site-navigation/logo.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/cosimameyer/
      weight: 1
    - icon: fa-github
      url: https://github.com/cosimameyer
      weight: 3
    #- icon: fa-twitter-square
    #  url: https://twitter.com/cosima_meyer
    #  weight: 4
    # - icon: fa-pinterest-square
    #   url: https://www.pinterest.com/
    #   weight: 3
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: monokailight
    tabWidth: 4
taxonomies:
  category: category
  tag: tags
outputs:
  home: ["HTML", "RSS", "JSON", "WebAppManifest"]
  section: [ "HTML", "RSS" ]
  taxonomy: [ "HTML", "RSS" ]
  taxonomyTerm: [ "HTML", "RSS" ]
ignoreErrors: ["error-remote-getjson"]